export const GET_INGREDIENT_ITEMS = "GET_INGREDIENTS";
export const GET_INGREDIENT_ITEMS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENT_ITEMS_FAILED = "GET_INGREDIENTS_FAILED";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
export const OPEN_INGREDIENT_ITEMS_MODAL = "OPEN_INGREDIENT_ITEMS_MODAL";
export const CLOSE_INGREDIENT_ITEMS_MODAL = "CLOSE_INGREDIENT_ITEMS_MODAL";
export const SELECT_INGREDIENT_ITEM = "SELECT_INGREDIENT_ITEM";
export const CHOOSE_TAB = "CHOOSE_TAB";
export const ADD_INGREDIENT_ITEM = "ADD_INGREDIENT_ITEM";
export const ADD_BUN_ITEM = "ADD_BUN_ITEM";
export const DECREASE_INGREDIENT_ITEM = "DECREASE_INGREDIENT_ITEM";
export const UPDATE_SELECTED_INGREDIENT_ITEMS =
  "UPDATE_SELECTED_INGREDIENT_ITEMS";
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR";
